In [70]:
import torch

## Q1

In [121]:
a = torch.Tensor([2]).requires_grad_(True)
b = torch.Tensor([3]).requires_grad_(True)

In [126]:
x = 2*a + 3*b
y = 5*a*a + 3*b*b*b

z = 2*x + 3*y

In [127]:
z.backward()

In [128]:
def analytical(a, b):
    return 4 + 30 * a

In [129]:
print(a.grad, analytical(a, b))
print(b.grad)

tensor([64.]) tensor([64.], grad_fn=<AddBackward0>)
tensor([249.])


## Q2 + Q3

In [141]:
def ReLU(x):
    return max(0, x)

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

b = torch.Tensor([1]).requires_grad_(True)
x = torch.Tensor([1]).requires_grad_(True)
w = torch.Tensor([1]).requires_grad_(True)

u = x * w
v = u + b
a = ReLU(v)
c = sigmoid(v)

In [142]:
def analytical_a(x, w, b):
    return x

def analytical_c(x, w, b):
    return sigmoid(x*w + b) * (1- sigmoid(w*x+b)) * x

In [139]:
a.backward()

print(w.grad, analytical_a(x, w, b))

tensor([1.]) tensor([1.], requires_grad=True)


In [143]:
c.backward()

print(w.grad, analytical_c(x, w, b))

tensor([0.1050]) tensor([0.1050], grad_fn=<MulBackward0>)


## Q4

In [84]:
x = torch.Tensor([5]).requires_grad_(True)

a = -1 * torch.sin(x)
b = -2*x
c = -1 * x ** 2

u = a + b + c
y = torch.exp(u)

In [85]:
y.backward()

print(x.grad)

tensor([-2.0206e-14])


## Q5

In [89]:
x = torch.Tensor([5]).requires_grad_(True)

y = 8 * x**4 + 3 * x**3 + 7 * x**2 + 6 * x + 3

In [90]:
y.backward()

x.grad

tensor([4301.])

## Q6

In [98]:
x = torch.Tensor([1]).requires_grad_(True)
y = torch.Tensor([2]).requires_grad_(True)
z = torch.Tensor([3]).requires_grad_(True)

In [110]:
a = 2*x
b = torch.sin(y)
c = a / b
d = c*z
e = torch.log(d+1)
f = torch.tanh(e)

In [100]:
f.backward()

print(x.grad)
print(y.grad)
print(z.grad)

tensor([0.0581])
tensor([0.0266])
tensor([0.0194])
