## Q1 - F.conv2D

In [17]:
import torch
import torch.nn.functional as F
import torch.nn as nn

image = torch.rand(1, 1, 6, 6)
print(image)
print(image.shape)
print('---')

kernel = torch.rand(1, 1, 3, 3)

outimage = F.conv2d(image, kernel, stride=1, padding=0)
print(outimage)
print(outimage.size())

tensor([[[[0.5346, 0.7714, 0.3719, 0.8360, 0.5781, 0.6845],
          [0.2050, 0.7051, 0.1959, 0.6867, 0.4436, 0.5854],
          [0.4251, 0.7226, 0.6444, 0.6268, 0.2365, 0.4054],
          [0.4202, 0.4937, 0.8623, 0.6452, 0.0246, 0.9901],
          [0.0829, 0.9093, 0.7794, 0.5133, 0.8842, 0.6364],
          [0.0800, 0.8497, 0.4085, 0.8312, 0.5820, 0.9909]]]])
torch.Size([1, 1, 6, 6])
---
tensor([[[[1.5648, 2.2782, 1.4313, 2.0411],
          [1.9578, 2.2583, 1.3454, 2.2665],
          [2.0126, 2.2678, 2.1763, 2.0761],
          [1.6518, 2.5919, 2.1477, 2.7438]]]])
torch.Size([1, 1, 4, 4])


## Q2 - nn.Conv2D vs F.conv2D

In [21]:
print('---')
print('Image')
print('---')
image = torch.rand(1, 1, 6, 6)
print(image)
print(image.shape)
print('---')
print('Outputs')
print('---')

m = nn.Conv2d(1, 3, 3, stride=1, padding=0, bias=False)
outimage_nn = m(image)

k = [n.data for n in m.parameters()][0]
outimage_F = F.conv2d(image, k, stride=1, padding=0)


print(outimage_nn)
print(outimage_nn.size())
print('---')
print(outimage_F)
print(outimage_F.size())

---
Image
---
tensor([[[[0.1963, 0.5757, 0.3885, 0.7981, 0.2324, 0.1389],
          [0.5888, 0.1574, 0.1147, 0.6467, 0.4757, 0.8957],
          [0.4251, 0.3464, 0.8903, 0.1398, 0.2894, 0.2301],
          [0.8477, 0.5820, 0.8107, 0.9635, 0.4911, 0.1770],
          [0.2641, 0.6290, 0.7383, 0.2848, 0.8211, 0.0257],
          [0.8565, 0.2940, 0.5266, 0.9157, 0.9420, 0.7643]]]])
torch.Size([1, 1, 6, 6])
---
Outputs
---
tensor([[[[-0.0608, -0.1556,  0.0898,  0.0770],
          [ 0.2823,  0.1176, -0.3721, -0.0634],
          [ 0.0163, -0.1133,  0.2568, -0.4145],
          [ 0.1980, -0.0814, -0.1377, -0.0283]],

         [[-0.5834, -0.3468, -0.5163, -0.4446],
          [-0.7003, -0.8488, -0.7547, -0.3851],
          [-0.6710, -0.8057, -0.8550, -0.6293],
          [-0.5483, -0.7581, -0.8762, -0.9860]],

         [[-0.1004,  0.0658,  0.1614,  0.1502],
          [-0.1830,  0.0450, -0.1704,  0.3452],
          [ 0.0906, -0.0585,  0.3177,  0.0575],
          [ 0.3370,  0.2679, -0.1367,  0.1809]]]],